version: '3.8'

services:
  app:
    image: minha-app
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "preview", "--", "--host", "--port", "5173"]
    volumes:
      - .:/app
      - /app/node_modules
